name: Deploy to Netlify (manual)

on:
  # Disabled automatic push trigger to avoid failing runs while secrets are not set.
  # The site is already linked to Netlify and will auto-deploy on push via Netlify's Git integration.
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Netlify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install netlify-cli
        run: npm install -g netlify-cli

      - name: Deploy to Netlify (production)
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          # Fail early if secrets are missing
          if [ -z "$NETLIFY_AUTH_TOKEN" ] || [ -z "$NETLIFY_SITE_ID" ]; then
            echo "NETLIFY_AUTH_TOKEN and NETLIFY_SITE_ID must be set in repository secrets." >&2
            exit 1
          fi
          npx netlify deploy --prod --dir=. --auth="$NETLIFY_AUTH_TOKEN" --site="$NETLIFY_SITE_ID"
